
def create_missing_invoices(env):
    missing_data = [
        {'vch': 'GDRM/25-26/02', 'date': '2025-04-08', 'partner': 'EASTERN RAILWAY JAMALPUR'},
        {'vch': 'GDRM/25-26/04', 'date': '2025-04-14', 'partner': 'Cancelled Record'},
        {'vch': 'GDRM/25-26/26', 'date': '2025-05-29', 'partner': 'Cancelled Record'},
        {'vch': 'GDRM/25-26/59', 'date': '2025-08-05', 'partner': 'Cancelled Record'},
        {'vch': 'GDRM/25-26/117', 'date': '2025-12-31', 'partner': 'Cancelled Record'},
        {'vch': 'GDRM/25-26/157', 'date': '2026-03-23', 'partner': 'Cancelled Record'},
        {'vch': 'GDRM/25-26/158', 'date': '2026-03-23', 'partner': 'Cancelled Record'},
    ]
    
    # 1. Get or create Cancelled Record partner
    cancelled_partner = env['res.partner'].search([('name', '=', 'Cancelled Record')], limit=1)
    if not cancelled_partner:
        cancelled_partner = env['res.partner'].create({'name': 'Cancelled Record'})
        print(f"Created partner: {cancelled_partner.name}")
    
    # 2. Get Eastern Railway partner
    eastern_partner = env['res.partner'].search([('name', '=', 'EASTERN RAILWAY JAMALPUR')], limit=1)
    
    # 3. Create invoices
    journal = env['account.journal'].search([('type', '=', 'sale')], limit=1)
    
    for data in missing_data:
        partner = eastern_partner if data['partner'] == 'EASTERN RAILWAY JAMALPUR' else cancelled_partner
        
        move_vals = {
            'move_type': 'out_invoice',
            'invoice_date': data['date'],
            'date': data['date'],
            'ref': data['vch'],
            'partner_id': partner.id,
            'journal_id': journal.id,
            'invoice_line_ids': [(0, 0, {
                'name': 'Cancelled Invoice Record',
                'quantity': 1,
                'price_unit': 0.0,
            })]
        }
        
        try:
            move = env['account.move'].create(move_vals)
            # Optional: move.action_post() then move.button_cancel()
            # But let's leave them draft or posted with 0 amount. 
            # If we post them, they get a sequence number. 
            # If the sequence number is important, we might need to be careful.
            # But here the 'name' will be generated by Odoo.
            print(f"Created Invoice {move.name} for {data['vch']}")
        except Exception as e:
            print(f"Error creating {data['vch']}: {e}")
            
    env.cr.commit()
    print("Creation complete.")

if __name__ == "__main__":
    create_missing_invoices(env)
